### ISSUE TITLE
pagination issue, not working on localhost:3000

### ISSUE THREAD

**Issue by techmarbles** [bigcommerce/cornerstone#1107]
### Expected behavior
when opening a category page, clicking page 2 should show next products.

### Actual behavior
showing 

{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

Under logs here is the error
[BS] Reloading Browsers...
Debug: internal, implementation, error 
    Error: Error: Response Error: 404 Not Found
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:46:31
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:220:28
    at read (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:530:24)
    at finish (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:350:20)
    at wrapped (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:875:20)
    at onReaderFinish (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:421:16)
    at g (events.js:292:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:512:14)
    at endWritable (_stream_writable.js:522:3)
    at Writable.end (_stream_writable.js:487:5)
Debug: internal, implementation, error 
    Error: Error: Response Error: 404 Not Found
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:46:31
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:220:28
    at read (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:530:24)
    at finish (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:350:20)
    at wrapped (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:875:20)
    at onReaderFinish (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:421:16)
    at g (events.js:292:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:512:14)
    at endWritable (_stream_writable.js:522:3)
    at Writable.end (_stream_writable.js:487:5)

### Steps to reproduce behavior

Clone default cornerstone theme, 

run following commands 
stencil init 
add your credentials
stencil start
then open any category page and click on page 2.

**Comment by jkelly-cas** [comment]
This issue is also happening to me. It's additionally happening on any non-existent page that generates a 404.

This is only happening on localhost. Once the theme is pushed, it seems to work fine.

stencil start Node Version: v8.5.0
npm -v : 5.3.0

**Comment by jkelly-cas** [comment]
As an addition for the pagination internal error, selecting the last page available results in that internal error. So if you have 6 pages 1 through 5 work fine, page 6 will error out.

**Comment by originsid** [comment]
Also having the same issue here, can't get to page 2 of a category when working locally. 

The only difference from what techmarbles described is that the standard 404 Error page is what shows (rather than a 500 error).

Cornerstone version 3.2.0
Node Version: v6.4.0
npm -v : 3.10.3

**Comment by originsid** [comment]
Tested this again today and it no longer appears to be an issue for me. I can get to page 2 of category pages when working locally now.

I can't confirm whether anything changed on my end or BigCommerce's end to solve this, but I don't think it was on my end. If it becomes a problem again then I'll post another update.

> Also having the same issue here, can't get to page 2 of a category when working locally.
> 
> The only difference from what techmarbles described is that the standard 404 Error page is what shows (rather than a 500 error).
> 
> Cornerstone version 3.2.0
> Node Version: v6.4.0
> npm -v : 3.10.3

**Comment by bc-zoharmuzafi** [comment]
Seems like this issue resolved.

**Comment by rordi** [comment]
Issue is not resolved

**Comment by diztinct-glenn** [comment]
Seems to still be unresolved to me as well. I don't get a 500 but rather a 404 whenever I try to go to the second page. Running on Cornerstone v4.12.1. Node v12.19.0

**Comment by ginagregory** [comment]
I am getting a 404 when trying to go to a paginated page (/shop-all/?sort=featured&page=2) on both localhost and the external IP link.

Cornerstone v6.2.0
Stencil v3.8.0 (macOS)
Node v12.22.8

**Comment by BC-krasnoshapka** [comment]
hi @ginagregory 
is your store available publicly and can you share the link?

**Comment by ginagregory** [comment]
@BC-krasnoshapka It's not, it's just a trial store. When I have Stencil running, this is the external link http://192.168.0.5:3000/shop-all/?sort=featured&page=2

**Comment by BC-krasnoshapka** [comment]
@ginagregory I'm afraid we're not able to help without your store configuration. I can't reproduce this problem. for example it's not reproduced on our demo store that uses Cornerstone 6.2.0 also - https://cornerstone-light-demo.mybigcommerce.com/shop-all/?sort=featured&page=2
