### ISSUE TITLE
Error: Uncaught error: Handlerbars Helper 'if' doesn't know the operator gtnum

### ISSUE THREAD

**Issue by ohabash** [bigcommerce/cornerstone#1366]
### Expected behavior
`stencil start` then see site on localhost instead i see
>{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

### Actual behavior
`stencil start` starts the server without error. But when i go to the http://localhost:3000/ the server errors with the following

>Debug: internal, implementation, error 
    Error: Uncaught error: Handlerbars Helper 'if' doesn't know the operator gtnum
    at Object.<anonymous> (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:86:23)
    at Object.4 (eval at <anonymous> (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:40), <anonymous>:21:32)
    at Object.prog [as inverse] (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at Object.<anonymous> (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:98:28)
    at Object.1 (eval at <anonymous> (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:40), <anonymous>:7:32)
    at Object.prog [as fn] (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at Object.<anonymous> (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:96:28)
    at Object.main (eval at <anonymous> (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:40), <anonymous>:39:32)
    at ret (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at Object.invokePartial (/Users/ohabash/.nvm/versions/node/v6.9.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)

### Steps to reproduce behavior

1. `npm install; npm init`
2. `stencil start`
3. error is first seen when trying to load http://localhost:3000

### Env
npm -v: => `4.6.1`
node -v => `v6.9.0`
stencil --version => `1.15.1`

**Comment by karen-white** [comment]
Hey @ohabash ,
Could you email me your theme files?

**Comment by ohabash** [comment]
@karen-white the problem was that another dev was trying to link to this component `{{> components/amp/common/store-logo}}`.. When I corrected the path, without amp - it worked.

Thank you
