### ISSUE TITLE
Local Testing for Google AMP Error: Uncaught error: Handlerbars Helper 'if' doesn't know the operator gtnum

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/cornerstone#1393]
### Expected behavior
Should be able to test Google amp pages locally with `localhost:3000/amp/product_url/`

### Actual behavior
`ebug: internal, implementation, error
    Error: Uncaught error: Handlerbars Helper 'if' doesn't know the operator gtnum
    at Object.<anonymous> (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:86:23)
    at Object.4 (eval at _.each (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:21), <anonymous>:21:32)
    at Object.prog [as inverse] (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at Object.<anonymous> (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:98:28)
    at Object.1 (eval at _.each (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:21), <anonymous>:7:32)
    at Object.prog [as fn] (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at Object.<anonymous> (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/helpers/if.js:96:28)
    at Object.main (eval at _.each (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-paper/index.js:130:21), <anonymous>:39:32)
    at ret (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at Object.invokePartial (/Users/petearevalo/.nvm/versions/node/v8.11.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)`

### File that is causing issue
Seems to be `templates/components/amp/common/store-logo.html` When I remove this file it works fine

###Cornerstone Version
2.2.1

**Comment by flair-duncan** [comment]
Your version of Bigcommerce/paper-handlebars is out of date, this comparison was added in [3.0.3](https://github.com/bigcommerce/paper-handlebars/releases/tag/v3.0.3).

You need to update your Stencil CLI, run `npm update -g @bigcommerce/stencil-cli`

**Comment by PeteyRev** [comment]
@flair-duncan oh wow, dunno how I missed that. Thanks
