### ISSUE TITLE
/assets/js/theme/common/product-details.js err

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/cornerstone#1473]
stencil bundle
Validating theme...
Running ESLint...

/assets/js/theme/common/product-details.js
  738:2  error  Newline required at end of file but not found  eol-last

✖ 1 problem (1 error, 0 warnings)

/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:274
            throw err;
            ^

Error: Please fix the above Javascript errors.
    at runLintTask (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/bundle-validator.js:267:18)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:3880:24
    at replenish (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:1011:17)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:1041:24)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:1046:16
    at _parallel (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:3879:5)
    at Object.series (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:4735:5)
    at BundleValidator.validateTheme (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/bundle-validator.js:55:11)
    at Bundle.validateTheme (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:272:20)

**Comment by karen-white** [comment]
Hey @bigmadness , are you still getting this ESLint error, even after adding a blank new line to the end of your productdetails.js file?

```
/assets/js/theme/common/product-details.js
738:2 error Newline required at end of file but not found eol-last
```

**Comment by junedkazi** [comment]
@karen-white can you open a PR with the above recommended fix ?

**Comment by bigmadness** [comment]
thank you @karen-white
