### ISSUE TITLE
Multiple choice options as rectangle boxes not working in IE11

### ISSUE THREAD

**Issue by slinc2** [bigcommerce/cornerstone#1649]
### Expected behavior
No error to show in the console.

### Actual behavior
There is an error appearing in the console.  

`jQuery.Deferred exception: Unable to get property '0' of undefined or null reference TypeError: Unable to get property '0' of undefined or null reference
   at Anonymous function (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.main.js:1140:13)
   at each (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.main.js:15397:2749)
   at setProductVariant (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.main.js:1089:5)
   at onReady (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.chunk.6.js:430:5)
   at Anonymous function (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.main.js:3564:7)
   at e (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.main.js:15397:29427)
   at Anonymous function (http://localhost:3000/stencil/00000000-0000-0000-0000-000000000001/dist/theme-bundle.main.js:15397:29737) undefin`

`SCRIPT5007: Unable to get property '0' of undefined or null reference
theme-bundle.main.js (15397,31100)`

`SCRIPT5007: Unable to get property '0' of undefined or null reference
theme-bundle.main.js (1140,13)`

### Steps to reproduce behavior
I am seeing this in Cornerstone V4.4.2 ( and 4.3.0).  This happens when you add an option to a product that is multiple choice and select the rectangle display style.  You then have to click on one of the rectangle options for the error to appear.  When it does it prevents any custom JS to function.

It appears to be caused around line 1140 and 15397 (Jquery section) of Theme-bundle.main.js. If I comment out this code it no longer throws an error but probably stops something else from working. It appears that "labels" is not defined or something.
`var label = checked.labels[0].innerText;`
            `if (label) {`
              `options.push(optionTitle + ":" + label);`
           ` }`

**Comment by obrien-k** [comment]
Hey there @slinc2 thanks for sharing this, I was able to replicate the issue with Cornerstone 4.3.0 as well, but with the latest version 4.5.0 it appears resolved.
