### ISSUE TITLE
Node Sass error on my Macbook with M1 chip

### ISSUE THREAD

**Issue by gaurishkamat** [bigcommerce/cornerstone#2385]
### Expected behavior

Though it starts the project locally I still get this error in the terminal. Also the project runs without styles. I am working on Node version 18.5.0, npm version 8.12.1.

### Actual behavior

```
Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 18.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v8.0.0
    at module.exports (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ScssCompiler.activateNodeSassEngine (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/lib/ScssCompiler.js:21:23)
    at StencilStyles.activateEngine (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/stencil-styles/lib/styles.js:51:36)
```

### Steps to reproduce behavior

npm install

stencil init

stencil start

**Comment by VladDlogush** [comment]
Hi, @gaurishkamat 
Try it **node v18.13.0**, **npm v9.5.1**, **stencil v7.0.0**

**Comment by gaurishkamat** [comment]
Hi  VladDlogush,

Thanks for your input. I tried with all the versions, it seems the issue was with the way I had installed node. Previously I had installed it with the Node.js installer from the node.js official website. Installing it with homebrew from the command line solved this issue.
